@baseUrl = http://localhost:6000

@urlPath = api/v1


###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "yasu",
  "password": "test123",
  "email": "yasu@gmail.com",
  "avatarColor": "red",
  "avatarImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "yasu",
  "password": "test123"
}
